### ISSUE TITLE
Is BotKit for Facebook available now?

### ISSUE THREAD

**Issue by Ayeps** [ramswaroop/jbot#1]
Please is the Facebook version available now

**Comment by ramswaroop** [comment]
Hey @Ayeps, thanks for reaching out but sorry to say that it still isn't available. I am working on the Slack Bot now and after it's completed I will start with Facebook and then Twitter.

**Comment by ramswaroop** [comment]
I have started working on this and the same can be found on branch `fbbot`.

**Comment by ramswaroop** [comment]
Closing this issue as JBot for facebook was released around a month ago. See [getting started instructions](https://github.com/ramswaroop/jbot/blob/master/docs/facebook/README-Facebook-JBot-4.0.0.md) to learn more.
