### ISSUE TITLE
Create a jar deliverable that can be used with maven/gradle

### ISSUE THREAD

**Issue by johkin** [ramswaroop/jbot#11]
It would be nice if there was a jar-file (published to central) that could be used as a gradle dependency, instead of cloning your repository!

**Comment by ramswaroop** [comment]
Hi,

It's already there. Search [maven central repository for jbot](https://search.maven.org/#search%7Cga%7C1%7Cjbot).

**Comment by johkin** [comment]
I tried to use that as a dependency, but since that is a spring-boot-jar, I'm having trouble using it as a dependency in my project? Is it possible to use it with gradle? The classes are placed under BOOT-INF/classes, which is kind of not a standard location for a jar-file...  :)
