### ISSUE TITLE
How to run in Eclipse IDE?

### ISSUE THREAD

**Issue by BooTemp** [ramswaroop/jbot#14]
This isn't an issue per se, but I'm having some issues running the sample application in Eclipse.  Are instructions documented someplace?

**Comment by ramswaroop** [comment]
It's simple as running any Java program with a `main()` method. Just run the `main()` method in [JBotApplication.java](https://github.com/ramswaroop/jbot/blob/master/jbot-example/src/main/java/example/jbot/JBotApplication.java)

**Comment by ramswaroop** [comment]
Hi,

[M2Eclipse](http://www.eclipse.org/m2e/) is the plugin which needs to be installed in your eclipse IDE as suggested by [Maven](https://maven.apache.org/ide.html). After that you can easily import the project as maven project and run it. You can refer to this [question on SOF](http://stackoverflow.com/questions/2061094/importing-maven-project-into-eclipse) to learn more.
