### ISSUE TITLE
Import JBot in Eclipse as a Java Project

### ISSUE THREAD

**Issue by JulienMrgrd** [ramswaroop/jbot#17]
Hi,

How can we import and launch your project (JBotApplication.java) directly in Eclipse ?
Actually, Eclipse can't detect that it's a Maven and Java project (so, your main classe cannot be launch, but as you said, if we launch the 'mvn spring-boot:run' command, it works).

Thanks for your help.

Julien M

**Comment by ramswaroop** [comment]
Hi,

[M2Eclipse](http://www.eclipse.org/m2e/) is the plugin which needs to be installed in your eclipse IDE as suggested by [Maven](https://maven.apache.org/ide.html). After that you can easily import the project as maven project and run it. You can refer to this [question on SOF](http://stackoverflow.com/questions/2061094/importing-maven-project-into-eclipse) to learn more.

**Comment by ramswaroop** [comment]
This question is somewhat related to https://github.com/ramswaroop/jbot/issues/14
