### ISSUE TITLE
Question regarding application.properties

### ISSUE THREAD

**Issue by X-509** [ramswaroop/jbot#18]
```
rtmUrl=https://slack.com/api/rtm.start?token={token}&simple_latest&no_unreads
slackBotToken=xoxb-50014402slackbottokenx29U9X1bQ
slashCommandToken=X73Fv3Tokenx242CdpEq
slackIncomingWebhookUrl=https://hooks.slack.com/services/T025DUwebhookurloOYvPiHL7y6
```

why in rtmUrl there is `{token}`. Do i have to replace it with one my application tokens from slack or what? 

similar question for `slashCommandToken`. I couldn't find it on slack website that i have to generate tokens for these.

**Comment by ramswaroop** [comment]
Hi,

As the README file says, you only have to place your **Slack token** in `slackBotToken` and your **Slack slash command token** in `slashCommandToken`. The `rtmUrl` will automatically be constructed from the tokens.
