### ISSUE TITLE
Post to channel on external event

### ISSUE THREAD

**Issue by CanardSauvage** [ramswaroop/jbot#20]
Hey,

I have a scheduler, which checks every hour if a new event (for example we sold something) occurred.

If something occurred, I want to send a new message to a channel (in which the bot already is).

Is this possible? I can't find any methods for this in the documentation.

**Comment by ramswaroop** [comment]
Hi,

Yes, it's there in the documentation. You can refer [Sending Messages](https://github.com/ramswaroop/jbot#sending-messages) section.
