### ISSUE TITLE
Dependency Resolution Exception

### ISSUE THREAD

**Issue by Stuartkenworthy** [ramswaroop/jbot#21]
I am trying to follow the instructions on offer and run the slackbot for the first time, I have navigated to jbot-example as stated and have run mvn spring-boot:run but when ever i do this i am presented with this error message:
[WARNING] The POM for me.ramswaroop.jbot:jbot:jar:3.0.3-SNAPSHOT is missing, no
dependency information available
[ERROR] Failed to execute goal on project jbot-example: Could not resolve depend
encies for project org.springframework.boot:jbot-example:jar:1.0.0-SNAPSHOT: Cou
ld not find artifact me.ramswaroop.jbot:jbot:jar:3.0.3-SNAPSHOT -> [Help 1]

I am quite new to mvn so I am not sure if i am doing something wrong or if there is an issue with the source i have downloaded, would greatly appreciate some assistance

**Comment by Stuartkenworthy** [comment]
Resolved the issue, mvn install needed to be ran in jbot directory before running spring-boot:run in jbot-example

**Comment by ramswaroop** [comment]
@Stuartkenworthy Glad you solved it 👍
