### ISSUE TITLE
Get Part of message

### ISSUE THREAD

**Issue by Stuartkenworthy** [ramswaroop/jbot#22]
My integration works perfectly if the user input just "@slackbotName message" with the code getting the input text and outputting the desired result based on this
However if the user inputs something before this such as "Hi '@slackbotName message'" the code reads all the text the user has typed not just the part following the "@" this causes the output to not display properly, is there anyway to get it so it only reads the message from the "@" onwards?

**Comment by Stuartkenworthy** [comment]
Found a way of fixing this issue, using .lastIndexOf() i can set it to ignore all text up to a specific symbol, this symbol being the "@" symbol for messaging the slackbot

**Comment by ramswaroop** [comment]
@Stuartkenworthy It would be better to use `indexOf()` instead of `lastIndexOf()` as the message can have `@` too.
