### ISSUE TITLE
Bot goes offline automatically

### ISSUE THREAD

**Issue by thirunar** [ramswaroop/jbot#24]
Hi, 

Thanks for the awesome framework. I'm using your framework to create a Slack Bot. I have an issue when the bot tries to reply back with large text (around 10k characters). The bot simply goes offline without any error. I tried debugging the issue, but couldn't get into a solution. 

I suspect, the web socket session is getting closed for larger text. I tried setting the text limit for the session, even that didn't work.

Can you help me fix the issue?

TIA!

**Comment by ramswaroop** [comment]
Can you please send me the logs. I don't think larger text would be the issue but this issue seems to be an exception in your code. I too faced such issue but later I figured out that there was an exception in my bot (the bot which I made using jbot and not jbot itself) code.

**Comment by thirunar** [comment]
The problem, there was not exception when the bot goes offiline. I'm attaching the code, let me know, if this helps

`    @Controller(events = {EventType.DIRECT_MENTION, EventType.DIRECT_MESSAGE})
    public void onReceiveDM(WebSocketSession session, Event event) {
        LOGGER.info("Received: {}", event.getText());

        String response = formatCode(requestProcessor.processRequest(event.getText()));
        reply(session, event, new Message(response));
        stopConversation(event);
    }
`
RequestProcessor.processRequest:

`    public String processRequest(String request) {
        RestTemplate restTemplate = new RestTemplate();
        HttpHeaders headers = createHeaders("admin", "xyz");
        String url = getUrl(request);
        if (url != null) {
            if (request.contains("livenodes")) {
                HttpEntity entity = new HttpEntity(headers);
                ResponseEntity<String> response = restTemplate.exchange(url, HttpMethod.GET, entity, String.class);
                return response.getBody();
            } else {
                headers.setAccept(asList(MediaType.APPLICATION_XML));
                HttpEntity entity = new HttpEntity(headers);
                try {
                    ResponseEntity<String> response = restTemplate.exchange(url, HttpMethod.GET, entity, String.class);
                    return PrettyPrinter.formatXML(response.getBody());
                } catch (Exception e) {
                    return "Sorry!! Error processing the request!!!";
                }
            }
        }
        return "";

    }
`

**Comment by ldavison** [comment]
See the [limits](https://api.slack.com/rtm#limits) section for RTM. It specifically says:

> The message server will disconnect any client that sends a message longer than 16 kilobytes. This includes all parts of the message, including JSON syntax, not just the message text.

**Comment by thirunar** [comment]
Thanks a lot!! This helps. I split the message into small chunks.
