### ISSUE TITLE
Running jbot-example fails with a NoClassDefFoundError

### ISSUE THREAD

**Issue by RobinsonZ** [ramswaroop/jbot#30]
I've been trying to run jbot-example–I cloned the repository, ran `mvn install` in the jbot folder, went into jbot-example and ran `mvn spring-boot:run`, but it throws this error:
```
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.0.RELEASE:run (default-cli) on project jbot-example: An exception occurred while running. 
null: InvocationTargetException: Error creating bean with name 'slackBot': Invocation of init method failed; 
nested exception is java.lang.NoClassDefFoundError: org/apache/tomcat/util/res/StringManager: org.apache.tomcat.util.res.StringManager -> [Help 1]
```

**Comment by ramswaroop** [comment]
Can you please provide the entire log?

**Comment by RobinsonZ** [comment]
Here it is:
[jbot-maven-log.txt](https://github.com/ramswaroop/jbot/files/686362/jbot-maven-log.txt)

**Comment by ramswaroop** [comment]
Thanks! What code changes have you done before running the above, have you modified `SlackBot.java` or can I see your fork which you're running?

**Comment by ramswaroop** [comment]
Then I guess you didn't build the dependency for `jbot-example` which is the`jbot` library itself.
Follow the below steps and let me know if this resolves the issue:
```bash
$ cd jbot/jbot
$ mvn clean install
$ cd ../jbot-example
$ mvn spring-boot:run
```

**Comment by ramswaroop** [comment]
I have also changed the dependency version for `jbot` in `jbot-example` pom.xml file from `3.0.3-SNAPSHOT` to `3.0.2`. This chnage won't require you to build `jbot` before running `jbot-example` anymore. Thanks!

**Comment by RobinsonZ** [comment]
Still failed to run with exactly the same error–I tried re-downloading the repository but it still doesn't work.

**Comment by RobinsonZ** [comment]
I'm going to try and reproduce this issue on a different computer with a clean install of Maven/Java and see what happens.

**Comment by ramswaroop** [comment]
If you took a fresh clone of the repo, just do the following:
```bash
$ cd jbot-example
$ mvn spring-boot:run
```
to make it work. But make sure you put the correct values in properties file before running. See README file for detailed instructions.

**Comment by RobinsonZ** [comment]
Just took a fresh clone, added token and webhook URL to application.properties, went into the jbot-example folder, and ran mvn spring-boot:run, and it still is having the same error.

**Comment by RobinsonZ** [comment]
I'm going to try and reproduce it on a different computer when I get home and see what happens.

**Comment by ramswaroop** [comment]
You can run with `--debug` option like `$ mvn spring-boot:run --debug` and paste the output here.

**Comment by RobinsonZ** [comment]
I tested it on my other computer and it appears to work fine (though it's doing some weird things when it connects, which is a separate thing) so it might be a problem with my Java installation. I'll see if I can figure it out tomorrow.
