### ISSUE TITLE
Slack now supports threaded messages! 

### ISSUE THREAD

**Issue by kajo404** [ramswaroop/jbot#32]
Are there any plans to include this feature in the bot? 

Sounds really cool
[message-threading](https://api.slack.com/docs/message-threading)

**Comment by ramswaroop** [comment]
@kajo404 Thanks for creating a ticket for this. I was thinking to include it. Not a major required to support this as Slack handles threaded messages in the same way it handles messages but it requires few more properties to be added in the `Event` model. Will add them now.

**Comment by ramswaroop** [comment]
Done. Have updated the Event and Message models. Happy threading 👍

**Comment by ean5533** [comment]
Is there anything wrong with thread support? My simple test app responds to thread messages by posting in the main channel. I can tell that a message is coming from a thread by checking `getThreadTs` but I cannot get it to post in-thread.

```
public void onReceiveMessage(WebSocketSession session, Event event) {
    reply(session, event, "test");  // does not go to thread when it should
}
```

Digging in to `Bot.reply` I don't see anywhere that `threadTs` is actually used for anything.
