### ISSUE TITLE
Restart required when chatting to new users

### ISSUE THREAD

**Issue by sunayansaikia** [ramswaroop/jbot#35]
Hi,
I have encountered a big issue. Say you entered a slack domain and it has several users. When a new user that haven't yet talked to the JBot, the JBot fails to take inputs. But when a restart of the spring-boot service is done, those users who tried interacting with the bots and failed are now are able to interact.
Can you please, tell me where can the problem be as soon as possible. :)

**Comment by ramswaroop** [comment]
Hmm, it never happened to me. Let others comment on it too. Will keep this issue open.

**Comment by sunayansaikia** [comment]
I'm trying ways to reproduce this? The only way I know is invite a new user to your team and you start messaging with him but you get no reply back! But once, you restart the spring boot service, the bot responds normally. I don't now may be the RTM API need to be polled? Is it what API is doing?

Please check this link out: https://www.fullstackpython.com/blog/build-first-slack-bot-python.html
Search exactly for the sentence -> _'The Slack client connects to the Slack RTM API WebSocket then constantly loops while parsing messages from the firehose'_

Is this related?

**Comment by sunayansaikia** [comment]
I was wrong on the Python thing. For the polling and all, your code handles that. I can see the method: 
`public final void handleTextMessage(WebSocketSession session, TextMessage textMessage)()`

Inside that, I get a `type=message` in the even object, but somehow, the event is not processed for the new users. I believe something related to the code below:
```
if (isConversationOn(event)) {
                invokeChainedMethod(session, event);
            } else {
                invokeMethods(session, event);
            }
```
If you don't mind would you mind guiding me on fixing this?

**Comment by ramswaroop** [comment]
Glad your issue is resolved.

**Comment by lurraca** [comment]
@sunayansaikia I am facing the same issue. What do you mean by 
> added the check for the `im_created` in the code.
?

**Comment by lurraca** [comment]
Ok, I think I got it. 

I made the change on the Jbot source code to check for `im_created` and add the channel to `DmChannels` list, so when that new user sends a direct message to the bot, jbot is able to determine that is a `DIRECT_MESSAGE`. @ramswaroop is this something that you would like me to send a PR to fix it?

**Comment by ramswaroop** [comment]
Hi @lurraca, looks like jbot should check for both the events. yes, you can send a PR for the fix. Thanks a mil for contributing. 👍

**Comment by mndominguez** [comment]
I'm having this same issue. @ramswaroop do you think you can merge the PR? If the issue is that @lurraca did not change the code to check both event types, I can go ahead and do it. Thanks, great project BTW!

**Comment by ramswaroop** [comment]
@mndominguez okay I will do that today 👍

**Comment by ramswaroop** [comment]
@mndominguez I just merged @lurraca PR #57.

**Comment by mndominguez** [comment]
@ramswaroop fantastic, thank you! Is the fix going to be on a new build on Maven Central?

**Comment by ramswaroop** [comment]
@mndominguez no it's not gone to maven yet. I will release it after some tests which may take some days as I am working on some new features as well.
