### ISSUE TITLE
App not runnning once deployed to Heroku

### ISSUE THREAD

**Issue by Stuartkenworthy** [ramswaroop/jbot#36]
After deploying to Heroku and attempting to run the app I am seeing this error message in the logs:
Error: Unable to access jarfile jbot-example/target/jbot-example-1.0.0-SNAPSHOT.jar

I have checked this is the correct name for the jar file and this is the jar file that is auto-created when running mvn spring-boot:run.

My procfile looks like this: web: java -Dserver.port=8080 -jar  jbot-example/target/jbot-example-1.0.0-SNAPSHOT.jar

And the path from the jbot directory to the jar file is jbot-example\target\jbot-example-1.0.0-SNAPSHOT.jar

Any help with this would be greatly appreciated

This is the first time I've used Heroku so not sure if I am missing anything.

**Comment by ramswaroop** [comment]
Well, from your comments I see that Heroku has forward slash in the path `/` and the path you specified has backward slash `\`. Can you please make sure that's not the issue?

**Comment by Stuartkenworthy** [comment]
I tried changing the slashes to how it is in jbot-example\target\jbot-example-1.0.0-SNAPSHOT.jar in the procfile and this removed the slashes in heroku altogether and showed up under the resources tab as 
jbot-exampletargetjbot-example-1.0.0-SNAPSHOT.jar

**Comment by Stuartkenworthy** [comment]
OK I moved the jar file to the root directory and this resolved the issue, now seeing:
no main manifest attribute, in jbot-example-1.0.0-SNAPSHOT.jar instead.

After googling it is saying that there should be a main-Class set in the manifest.mf file inside the jar, this does not exist, should this not have automatically been set when the jar was created?

**Comment by ramswaroop** [comment]
You need move any jar files. It would mess things up. Have you followed the steps mentioned in the [docs](https://github.com/ramswaroop/jbot#deploy-to-the-cloud)?

**Comment by Stuartkenworthy** [comment]
Have resolved the issue, problem was that the jar did not contain org.springframework.boot dependencies
added - <build>
  <plugins>
    <plugin>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-maven-plugin</artifactId>
    </plugin>
  </plugins>
</build>
to the pom.xml in jbot-example, repackaged and this worked properly.

**Comment by ramswaroop** [comment]
So you mean there are dependencies missing from **jbot-example**? I will take a look at it this weekend and try to fix.

**Comment by Stuartkenworthy** [comment]
Yes thats correct, I have attached the link to the article I found that showed me how to solve this issue:
http://docs.spring.io/spring-boot/docs/current/reference/html/getting-started-first-application.html
Point 11.5 shows the change I made.

**Comment by ramswaroop** [comment]
Okay, if it's really an issue then I think it wouldn't even build locally but it is. I will give it a look and come back to you.

**Comment by talbright** [comment]
The directions on the README for heroku do not work correctly. While @Stuartkenworthy is right that the fix for `no main manifest attribute, in jbot-example-1.0.0-SNAPSHOT.jar` is adding the `spring-boot-maven-plugin` to the `pom.xml`, my solution for the other issue was to modify the `Procfile`:

```
web: java -Dserver.port=8080 -jar  jbot-example/target/jbot-example-1.0.0-SNAPSHOT.jar
```

**Comment by ramswaroop** [comment]
Thanks @talbright , it makes sense. Can we also do something around the jar file name in the Procfile such that everytime I update the jbot-example jar I don't have to edit the Procfile.

**Comment by talbright** [comment]
That seems to be the next logical step, to do something around automating version changes. Alternatively, it might just be better to go with deploying directly to heroku: https://devcenter.heroku.com/articles/deploying-java-applications-with-the-heroku-maven-plugin

But I haven't had time to work through that approach yet but will in the next couple of weeks and can push a fix when I figure out the best way to do it.

For now you shouldn't have to update `Procfile` that often -- only when you change the version of `jbot-example/pom.xml`. So far from git log it doesn't look like you have changed it yet, so it should be stable for the meantime. 

I would suggest merging this in now since it fixes an immediate issue, and we can work on a better long term solution in another PR.

**Comment by ramswaroop** [comment]
Yes @talbright, I am reviewing the PR now.

**Comment by ShinkarevPavel** [comment]
`web: java -Dserver.port=$PORT -jar  jbot-example/target/jbot-example-1.0.0-SNAPSHOT.jar`
@talbright , thank you so much for this tip. I spent a lot of time looking for a solution error of jarfile access. You are my savior.

**Comment by ItSeemsToWork** [comment]
> `web: java -Dserver.port=$PORT -jar jbot-example/target/jbot-example-1.0.0-SNAPSHOT.jar` @talbright , thank you so much for this tip. I spent a lot of time looking for a solution error of jarfile access. You are my savior.

в двух словах обьясни в чем ошибка и что нужно предпринять?)
