### ISSUE TITLE
Flushing the waiting queue when restarting the app server

### ISSUE THREAD

**Issue by ashfack** [ramswaroop/jbot#40]
Good afternoon,

First of all, thanks for your work and making it available on Git. I am currently trying to use Jbot, it works pretty fine. However, when restarting the server, not only are the pending request all replied at once but some messages for which a reply have already been made are sent again. Would there be a way to handle this?

Advanced thanks,

**Comment by ramswaroop** [comment]
Hi @ashfack, JBot doesn't use any persistent storage to store the queue. Therefore, the queue is empty when you restart the bot. It happens the way you're saying only because slack sends recent previous events when a client connects to it. Hope you get the problem here.

**Comment by ramswaroop** [comment]
As a solution, you can check the time of the event and if it's more than a certain time, you can ignore them in your code.

**Comment by ashfack** [comment]
Thank you very much, it is what my research lead me too.

Have a nice day.
