### ISSUE TITLE
Field ts is missing from Item

### ISSUE THREAD

**Issue by laci0725** [ramswaroop/jbot#46]
I found out while playing with reaction_added event that there is one field that is missing from the Item which is called ts. It is the time stamp of the original message which received the reaction. Whitout this field it is not possible to determine which message received the reaction. I added it to Item in local and it works like a charm, maybe itt would be great to fix this issue here as well.

**Comment by ramswaroop** [comment]
@laci0725 it would be great if you can raise a pull request on github. I can merge it asap.

**Comment by laci0725** [comment]
It is done.

**Comment by ramswaroop** [comment]
Closed with PR #47 .
