### ISSUE TITLE
How to make bot "reply with typing"

### ISSUE THREAD

**Issue by abstract-karshit** [ramswaroop/jbot#48]
Hi, Like howdy botkit, I wanted to send messages from jbot using reply with typing feature.
I have set message type as "typing" but still the bot directly replies without a **typing** info before.

**Comment by ramswaroop** [comment]
Yes, if you reply with type as `typing` then it should work. It may not be working in some cases where in no time you send back a reply with type `message`. Are you sure you're not sending a reply with type `message` instantly after `typing`?

**Comment by abstract-karshit** [comment]
Thanks for the reply. Yes Its working, when I went through your **reply method** it was resetting the message type so I have written a custom reply method using reply method as reference and it works like a charm.

**Comment by ramswaroop** [comment]
@abstract-karshit but the `reply()` method is final. Did you modify the library to get it working? I think this maybe an issue which needs to be solved. I can set the type to `message` only if it isn't set by the user or something.

**Comment by ramswaroop** [comment]
I thought while replying back, the type will be always `message` which is not. So I think its a minor bug.

**Comment by abstract-karshit** [comment]
Yes, reply method is final. I re-wrote the method in a my own class BotUtils.
Yes, I think we should set the type only when it isn't set by the user, I didn't modified the source code as I am using it as a maven dependency.
Also, one more thing to point out is when we **encode** message, the user mention is not working.
<@userId> doesn't works, so I removed **encode** in my version of the message.
