### ISSUE TITLE
Markdown attribute missing in Attachment

### ISSUE THREAD

**Issue by abstract-karshit** [ramswaroop/jbot#51]
The generic model for attachment should also have attribute for markdown.
For eg:
```javascript
{
  "attachments": [
    {
      "title": "Help Documentation",
      "title_link": "https://docs.google.com/xxxx/usp=sharing",
      "text": "Here is a quick guide of what I can do",
      "color": "#7CD197",
      "mrkdwn_in": [
        "text",
        "pretext"
      ]
    }
  ]
}
```
Markdown is an array of string and allows users to format the within attachment as well.

**Comment by ramswaroop** [comment]
PR merged with master. Thanks very much for the contribution, really appreciate it 👍 .

**Comment by c1aran** [comment]
Am I stupid or is this attribute/method missing in the latest Maven Repository (3.0.2)? :(
