### ISSUE TITLE
Conversations won't end conversation properly.

### ISSUE THREAD

**Issue by pwatter1** [ramswaroop/jbot#53]
![screenshot from 2017-06-22 13-34-13](https://user-images.githubusercontent.com/14846130/27447592-8ea27862-574f-11e7-8ccd-78b7aab5f695.png)
This about sums it up. I love your library but I can't end conversations properly and i dont know why.

    @Controller(pattern = "(setup poll)", next = "comfirm")
    public void onPollRequest(WebSocketSession session, Event event)
    {
        startConversation(event, "confirm");
        reply(session, event, new Message("'Yes' to confirm setup poll."));
    }

    @Controller(next = "runPoll")
    public void confirm(WebSocketSession session, Event event)
    {
        if(event.getText().contains("yes")) {
            reply(session, event, new Message("Awesome! Which system?  -BA -UCD -Machines -Jenkins -Sametime"));
            nextConversation(event);
        } else {
            stopConversation(event);
        }
    }

    /**
     * This method is chained with {@link SlackBot#onPollRequest(WebSocketSession, Event)}.
     *
     * @param session
     * @param event
     */
    @Controller
    public void runPoll(WebSocketSession session, Event event)
    {
        if (event.getText().contains("Jenkins")) {
            reply(session, event, new Message("Easy, running..."));
            ResourcePollingMachine.runRPM("Jenkins", true, true);
        } else if (event.getText().contains("BA")) {
            reply(session, event, new Message("Easy, running..."));
            ResourcePollingMachine.runRPM("BA", true, true);
        } 
        stopConversation(event);
    }

**Comment by ramswaroop** [comment]
Hi, I see a typo in the first line. `comfirm` should be `confirm` I guess. And also going through this issue https://github.com/ramswaroop/jbot/issues/40 may be worth it.

**Comment by pwatter1** [comment]
Hi, thanks for getting back to me. I did have a typo lol. Unfortunately that wasn't the cause of the issue. I checked the referenced issue and it seems similar. I tried messing with recording the Timestamp of the initial event that starts the conversation and only sending the message if it was the creator, but it didnt resolve it as I think it gets a new time stamp each time its called. This leads me to believe that the start method is called instead of stopping the conversation. Could you give a general example on how you were suggesting on using the timestamps to mitigate the issue? Thanks!

**Comment by pwatter1** [comment]
I think the issue is that the App is reply with the status of the systems, maybe it's interrupting the conversation since its a "different" user?  I attached the bot to the App. I have it now check if it's a valid system before polling and if it isnt valid, it ends the conversation as instructed. Which leads me to believe it may be the app.

**Comment by pwatter1** [comment]
The issue was how i was using your application, I was asking it to poll systems and a seperate function was throwing a webhook in the middle of the conversation, which seemed to confuse jbot and I simply changed how i used Jbot. My question now is if i wanted to use a different javac version to compile the jbot source files, not jbot-example. How would I go about doing this with maven? I'm running the project on our company server that does not have java 8 and its running into issues. Thank you.
