### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by codelibra** [ramswaroop/jbot#55]
Hi Jbot dev,

I wanted to post a welcome message when a new user joins the team. The team_join event is getting fired properly but the channelId is coming null and hence no welcome message is posted.
Could you point me in the right direction here?

Thanks

**Comment by ramswaroop** [comment]
You can listen to the `team_join` event where you get the `user` object which you can use to send the greeting message. See [slack api](https://api.slack.com/events/team_join) to learn more.
