### ISSUE TITLE
Bot(app) is installed in slack team. But when a user adds the app, no response unless the JBOT is restarted.

### ISSUE THREAD

**Issue by tcarlson25** [ramswaroop/jbot#65]
whenever someone adds the app to talk to the bot, and they havn't talked to it before, it doesn't respond at all. Only if I reboot the app on my machine will it then allow them to talk to it. Not sure why or how to fix it...

**Comment by tcarlson25** [comment]
already resolved in another closed issue

**Comment by ramswaroop** [comment]
If you can link the solved issue here then it would help others.

**Comment by tcarlson25** [comment]
Solution here: https://github.com/ramswaroop/jbot/issues/35
