### ISSUE TITLE
How to get App installed and running on multiple slack teams??

### ISSUE THREAD

**Issue by tcarlson25** [ramswaroop/jbot#67]
I have made a bot within an app and have the slack button working that makes the appropriate API call to allow the slack team to install it, but whenever I do this twice, it takes it off of the first team that was installed. I'm assuming this is because of the slack bot token, but not sure how to fix or how to go about this issue. Any help would be great, thanks.

**Comment by tcarlson25** [comment]
@ramswaroop Would you happen to know anything about this issue, or have encountered this before?

**Comment by ramswaroop** [comment]
This is weird as earlier Slack apps were by default in "one team" mode but from Feb 2017 the default mode is "all teams". Just check your app settings whether it's restricted to one team only. Read the [slack docs for making slack apps](https://api.slack.com/slack-apps#creating_apps) to learn more.
