### ISSUE TITLE
[Question] How is a user name retrieved from an event?

### ISSUE THREAD

**Issue by Eunanibus** [ramswaroop/jbot#85]
As Slack only responds with the user ID, how are users able to retrieve the real name of the individual interacting with the bot?

**Comment by ramswaroop** [comment]
There are two ways to do this, there may be more.

1. When `rtm.start()` is invoked when the bot starts, slack returns you a list of existing user objects in the team. You can create a hashmap of these user objects with user ids as the key. See [rtm.start()](https://api.slack.com/methods/rtm.start) to learn more.
2. You can use Slack's web API to retrieve user info by passing the token and user id. See [user.info](https://api.slack.com/methods/users.info) to learn more.

Hope this helps!
