### ISSUE TITLE
Delayed response to slash commands

### ISSUE THREAD

**Issue by Eunanibus** [ramswaroop/jbot#90]
In your documentation, there's no clear example of how to deal with responding to slash commands if it exceeds the 3000ms response time. Is there a method by which the 200 response can be sent, and later the RichMessage?

**Comment by ramswaroop** [comment]
You can send a 200 OK response like `ResponseEntity.ok("");` or `new ResponseEntity().status(HttpStatus.OK);` whichever you like.

**Comment by Eunanibus** [comment]
This makes sense. But how, when you don't receive a websocket as a parameter slash command method, do you return this response code, and then later send the message? Can you provide an example of this?

**Comment by ramswaroop** [comment]
That's easy. You can move your time-taking logic to a different method and pass the [response url](example/jbot/slack/SlackSlashCommand.java:66) you get initially. You can then later make a POST call to this response url. See [delayed and multiple responses on Slack](https://api.slack.com/slash-commands).
