### ISSUE TITLE
Would you like to have Skype/Kik/Telegram integration in JBot?

### ISSUE THREAD

**Issue by ramswaroop** [ramswaroop/jbot#91]
I am opening this issue to know the user's view/choice of the next integration. Please kindly do a thumbs up to whichever service you'd like to integrate JBot with.

P.S: I have plans on integrating only one more service in JBot for the time being.

**Comment by ramswaroop** [comment]
Skype

**Comment by ramswaroop** [comment]
Kik

**Comment by ramswaroop** [comment]
Telegram

**Comment by asm0dey** [comment]
Looks like Telegram is the winner :)

**Comment by ramswaroop** [comment]
I am on it.
